name: Grant Permissions

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to grant permissions'
        required: true

jobs:
  grant-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Grant Permissions
        run: |
          # Replace <your-organization> and <your-repo> with your organization and repository name
          REPO="EGaDSAustin/JJ-0"
          USERNAME="${{ github.event.inputs.username }}"
          
          # Get the user's ID
          USER_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/$USERNAME" | jq -r .id)
          
          # Add the user as a collaborator
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO/collaborators/$USER_ID" -d '{"permission":"push"}'
