name: Grant Permissions

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to grant permissions'
        required: true

jobs:
  add-collaborator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add collaborator
        run: |
          REPO_OWNER="texas-egads"
          REPO_NAME="JJ-0"
          USERNAME="grizzledwarvet23"
          GH_TOKEN="${{ secrets.GH_TOKEN }}"

          # Get the user's ID
          USER_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/users/$USERNAME" | jq -r .id)

          # Add the user as a collaborator
          curl -X PUT -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/collaborators/$USERNAME" \
            -d "{\"permission\":\"write\"}"

        env:
          USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
